version: 2
sources:
  - name: RAW_SOURCE
    description: This is RAW_TEST Database Source Tables used for creating STANDARD_TEST Layer
    database: DBT
    tables:
      - name: CUSTOMER
      - name: ORDERS
      - name: LINEITEM
      - name: NATION
      - name: PART
      - name: PARTSUPP
      - name: REGION
      - name: SUPPLIER
  - name: STAGE
    description: This is RAW_TEST Database Source Tables used for creating STANDARD_TEST Layer
    database: DBT
    tables:
      - name: CUSTOMER
      - name: ORDERS
      - name: LINEITEM
      - name: NATION
      - name: PART
      - name: PARTSUPP
      - name: REGION
      - name: SUPPLIER
